version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: flatiron_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flatiron_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: flatiron_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - flatiron_network

networks:
  flatiron_network:
    driver: bridge
